In [1]:
import pandas as pd

df = pd.DataFrame({
    "Age": [22, None, 28, 22],
    "Salary": [30000, 45000, None, 30000],
    "City": ["Delhi", "Mumbai", "Delhi", "Delhi"]
})
df

    Age   Salary    City
0  22.0  30000.0   Delhi
1   NaN  45000.0  Mumbai
2  28.0      NaN   Delhi
3  22.0  30000.0   Delhi

In [ ]:
a =df.isnull()
a.sum()
print(a.sum())
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Salary"] = df["Salary"].fillna(df["Salary"].median())
print(df)

Age       1
Salary    0
City      0
dtype: int64
0    22.0
1    24.0
2    28.0
3    22.0
Name: Age, dtype: float64
0    30000.0
1    45000.0
2    30000.0
3    30000.0
Name: Salary, dtype: float64
    Age   Salary    City
0  22.0  30000.0   Delhi
1  24.0  45000.0  Mumbai
2  28.0  30000.0   Delhi
3  22.0  30000.0   Delhi

0    False
1    False
2    False
3     True
dtype: bool

In [ ]:
print(df.duplicated().sum())
df.drop_duplicates(inplace=True)

    Age   Salary    City
0  22.0  30000.0   Delhi
1  24.0  45000.0  Mumbai
2  28.0  30000.0   Delhi

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["City"] = le.fit_transform(df["City"])

    Age   Salary  City
0  22.0  30000.0     0
1  24.0  45000.0     1
2  28.0  30000.0     0

In [35]:

from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()
df[["Age", "Salary"]] = scaler.fit_transform(df[["Age", "Salary"]])
print(df)

        Age    Salary  City
0 -1.069045 -0.707107     0
1 -0.267261  1.414214     1
2  1.336306 -0.707107     0